#ifndef INC_INCLUDEH_
#define INC_INCLUDEH_

#define LED_R_CHANNEL TIM_CHANNEL_1
#define LED_B_CHANNEL TIM_CHANNEL_2
#define LED_G_CHANNEL TIM_CHANNEL_3
#define LED_TIMER_HANDLE htim2

#define MOTOR_TIMER_HANDLE htim3
#define MOTOR_TIMER_CHANNEL TIM_CHANNEL_1


#endif /* INC_INCLUDEH_ */