M48
; DRILL file {KiCad 9.0.1} date 2025-05-09T16:55:24+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-09T16:55:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.020
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.450
%
G90
G05
T1
X73.835Y-89.79
X73.835Y-101.79
T2
X132.581Y-89.039
X132.581Y-99.691
T3
X84.343Y-72.65
M30
